### PR TITLE
Added terraform configuration to setup RG and AKS cluster

### PR DESCRIPTION
**Pull request by thomas-hennessy-work**

### CODE REVIEW

**Review by ryanpurchase288 — CHANGES_REQUESTED** [review]
Still have unnecessary files or incorrect names still in there

**Review by kirankalsi — COMMENTED** [review]
I agree with Ryan

**Review by ryanpurchase288 — APPROVED** [review]
very good. I approve of these changes

**Review by kirankalsi — APPROVED** [review]
looks good!

**Pull request merged**
